TEMP_TIMD_COMP_KEYS = {
    'A': 'matchNumber',
    'B': 'teamNumber',
    'C': 'assignmentMode',
    'D': 'scoutKey',
    'E': 'driversStation',
    'F': 'isReplay',
    'G': 'isNoShow',
    'H': 'startLevel',
    'I': 'preloadPiece',
    'J': 'leftHab',
    'K': 'actionType',
    'L': 'actionPlace',
    'M': 'actionTime',
    'N': 'actionPiece',
    'O': 'placeLevel',
    'P': 'wasDefended',
    'Q': 'cargoShipSide',
    'R': 'actualClimb',
    'S': 'attemptedClimb',
    'T': 'isDoubleClimb',
    'U': 'isTripleClimb'
}

TEMP_TIMD_COMP_VALUES = {
    't': True,
    'f': False,
    'a': 'file',
    'b': 'override',
    'c': 'red1',
    'd': 'red2',
    'e': 'red3',
    'g': 'blue1',
    'h': 'blue2',
    'i': 'blue3',
    'j': 'hab1',
    'k': 'hab2',
    'l': 'cargo',
    'm': 'hatch',
    'n': 'none',
    'o': 'humanPlayerStation',
    'p': 'ground',
    'q': 'intake',
    'r': 'place',
    's': 'level1',
    'u': 'level2',
    'v': 'level3',
    'w': 'front',
    'x': 'side',
    'y': 'rocket',
    'z': 'cargoShip',
    'aa': 'drop',
    'ab': 'middleField',
    'ac': 'incap',
    'ad': 'recap',
    'ae': 'climb',
    'af': 'defenseStart',
    'ag': 'defenseEnd',
}

